---
title: "proyekprakds"
author: "ahmfarhan - 123200100"
date: "2022-11-26"
output: pdf_document
---

```{r}
library(tm) #Untuk membersihkan data
library(vroom) #Load Dataset
library(here) #Menyimpan Dataser
```

```{r}
d <- vroom(here('ReviewRiliv.csv'))
ulasan <- d$h3YV2d
ulasan1 <- Corpus(VectorSource(ulasan))
removeNL <- function(y) gsub("\n", " ", y)
reviewclean <- tm_map(ulasan1, removeNL)
replacecomma <- function(y) gsub(",", "", y)
reviewclean <- tm_map(reviewclean, replacecomma)
removetitik2 <- function(y) gsub(":", "", y)
reviewclean <- tm_map(reviewclean, removetitik2)
removetitikkoma <- function(y) gsub(";", " ", y)
reviewclean <- tm_map(reviewclean, removetitikkoma)
remove.all <- function(xy) gsub("[^[:alpha:][:space:]]*", "", xy)
reviewclean <- tm_map(reviewclean, remove.all)
reviewclean <- tm_map(reviewclean, removePunctuation)
reviewclean <- tm_map(reviewclean, tolower)
dataframe <- data.frame(text=unlist(sapply(reviewclean,`[`)),stringsAsFactors = F)
View(dataframe)
write.csv(dataframe,file = 'ReviewRilivClean.csv')

```

