---
title: "Sentiment Analysis"
author: "123200100-123200045"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(e1071)
library(caret)
library(syuzhet)
library(shiny)
library(vroom)
library(here)
library(ggplot2)
library(dplyr)
library(here)
library(plotly)

databersih <- read.csv("D:/SEMESTER 5/PRAK DATA SCIENCE/sumber/ReviewRilivClean.csv", stringsAsFactors = FALSE)
komentar <- as.character(databersih$text) #mengubah objek numerik menjadi objek karakter
s <- get_nrc_sentiment(komentar) #Mengkategorikan kedalam 10 emosi sentiment berbeda

komentar_gabungan <- cbind(databersih$text,s) #menggabungkan dua data frame bersama jika jumlah baris di kedua frame data sama
par(mar = c(4,4,4,4))
a <- barplot(colSums(s), col=rainbow(10), xlab ='Jenis Sentiment', ylab='Jumlah Kata', main='Sentiment Anaylsis')
brplt <- a
```

```{r}
#Skoring
skoring <- read.csv('D:/SEMESTER 5/PRAK DATA SCIENCE/sumber/ReviewRilivClean.csv', header = TRUE)
View(skoring)

kata.positif <- scan("D:/SEMESTER 5/PRAK DATA SCIENCE/sumber/positivewords.txt",what="character",comment.char=";")
kata.negatif <- scan("D:/SEMESTER 5/PRAK DATA SCIENCE/sumber/negativewords.txt",what="character",comment.char=";")
score.sentiment = function(sentence, positif, negatif,
                           .progress='none')
{
  require(plyr)
  require(stringr)
  scores = laply(sentence, function(kalimat, positif,
                                    negatif) {
    kalimat = gsub('[[:punct:]]', '', kalimat)
    kalimat = gsub('[[:cntrl:]]', '', kalimat)
    kalimat = gsub('\\d+', '', kalimat)
    kalimat = tolower(kalimat)
    list.kata = str_split(kalimat, '\\s+')
    kata2 = unlist(list.kata)
    positif.matches = match(kata2, kata.positif)
    negatif.matches = match(kata2, kata.negatif)
    positif.matches = !is.na(positif.matches)
    negatif.matches = !is.na(negatif.matches)
    score = sum(positif.matches) - (sum(negatif.matches))
    return(score)
  }, kata.positif, kata.negatif, .progress=.progress )
  
  scores.df = data.frame(score=scores, text=sentence)
  return(scores.df)}

hasil = score.sentiment(skoring$text, kata.positif, kata.negatif)

#konversi score ke sentiment
hasil$klasifikasi<- ifelse(hasil$score<0, "Negatif",ifelse(hasil$score==0,"Netral","Positif"))
hasil$klasifikasi
View(hasil)

#menukar urtan baris
data <- hasil[c(3,1,2)] #ubah urutan kolom
View(data)
write.csv(data, file = "datalabel3.csv")
```

```{r}
library(tm)
library(RTextTools)
library(dplyr)
library(wordcloud)
library(naivebayes)
library(devtools)
library(gmodels)

data.frame <- read.csv("datalabel3.csv",stringsAsFactors = F)
data.frame$klasifikasi <- factor(data.frame$klasifikasi)
glimpse(data.frame)
set.seed(20)
data.frame<-data.frame[sample(nrow(data.frame)),]
data.frame<-data.frame[sample(nrow(data.frame)),]
glimpse(data.frame)
corpus<-Corpus(VectorSource(data.frame$text))
corpus
inspect(corpus[1:10])

#fungsinya untuk membersihkan data data yang tidak dibutuhkan 

corpus.clean<-corpus %>%
  tm_map(content_transformer(tolower)) %>% #digunakan untuk mengubah huruf besar dari string menjadi string huruf kecil
  tm_map(removePunctuation)%>% #menghapus tanda baca
  tm_map(removeNumbers)%>% #menghapus nomor
  tm_map(removeWords,stopwords(kind="en"))%>% #menghapus stopwords
  tm_map(removeWords, c("app", "saya", "bisa", "ini", "dan", "sangat", "aku" ,"untuk", "kalau", "tapi", "banget", "sih", "sudah", "masih","itu", "ada","yang","saja","tidak","nya","juga","dari","gak","aja","lebih"))%>%
  tm_map(stripWhitespace) 
dtm<-DocumentTermMatrix(corpus.clean)
inspect(dtm[1:10,1:20])

df.train<-data.frame[1:600,]
df.test<-data.frame[601:800,]   

dtm.train<-dtm[1:600,]
dtm.test<-dtm[601:800,]

corpus.clean.train<-corpus.clean[1:600]
corpus.clean.test<-corpus.clean[601:800]

dim(dtm.train)

fivefreq<-findFreqTerms(dtm.train,5)
length(fivefreq)

dtm.train.nb<-DocumentTermMatrix(corpus.clean.train,control = list(dictionary=fivefreq))
dim(dtm.train.nb)

dtm.test.nb<-DocumentTermMatrix(corpus.clean.test,control = list(dictionary=fivefreq))
dim(dtm.test.nb)

#Boolan Naive Bayes
convert_count <- function(x){
    y<-ifelse(x>0,1,0)
    y<-factor(y,levels=c(0,1),labels=c("no","yes"))
    y
}

#Naive Bayes Model
trainNB<-apply(dtm.train.nb,2,convert_count)
testNB<-apply(dtm.test.nb,2,convert_count)

classifier <- naiveBayes(trainNB, df.train$klasifikasi, laplace = -1)

#Use the NB classifier we built to make predictions on the test set
pred <- predict(classifier, testNB)

#Create a truth table by tabulating the predicted class labels with the actual predicted class labels with the actual class labels
NB_table=table("Prediction"= pred, "Actual" = df.test$klasifikasi)
NB_table

#confussion Matrix
conf.matNB <- confusionMatrix(pred, df.test$klasifikasi)
conf.matNB

```

```{r}
#Word Cloud
layout(matrix(c(1, 2), nrow=2), heights=c(1, 4))
par(mar=rep(0, 4))
plot.new()
text(x=0.5, y=0.5, cex=1.5, "Word Cloud")
wordcloud(corpus.clean,max.words = 100,random.order=F,colors=brewer.pal(8,"Dark2"))

```

```{r}
reviewriliv <- read.csv(file="D:/SEMESTER 5/PRAK DATA SCIENCE/sumber/ReviewRilivClean.csv",header=TRUE)

kataorang <- reviewriliv$text

ui <- fluidPage(
  titlePanel("Sentiment Analysis tentang Review Aplikasi Riliv"), #halaman judul dr fluid page
  mainPanel( 
    #tab pada fluidpage
    #plot output : untuk barplot
    tabsetPanel(type = "tabs",
                tabPanel("Bar Plot", plotOutput("scatterplot")), #tab berupa scatterplot/grafik
                tabPanel("Data Review", DT::dataTableOutput('tbl')), #tab berupa data clening 
                tabPanel("Word Cloud", plotOutput("Wordcloud")) #tab berupa worldcloud
    )
  )
)

# SERVER
# Disinialah tempat dimana data akan dianalisis dan diproses lalu hasilnya akan ditampilkan atau diplotkan pada bagian mainpanel() ui yang telah dijelaskan sebelumnya.
server <- function(input, output) {
  # Output Data
  output$tbl = DT::renderDataTable({ 
    DT::datatable(reviewriliv, options = list(lengthChange = FALSE)) # data akan ditampilkan dalam beberapa halaman.
    })
  
  #Barplot
  output$scatterplot <- renderPlot({rilivdata<-read.csv("D:/SEMESTER 5/PRAK DATA SCIENCE/sumber/ReviewRilivClean.csv",stringsAsFactors = FALSE)
  komentar <-as.character(rilivdata$text)
  s<-get_nrc_sentiment(komentar)
  review_combine<-cbind(rilivdata$text,s)
  par(mar=c(4,4,4,4))
  barplot(colSums(s),col=rainbow(10),ylab='Jumlah Kata',xlab = "Jenis Sentiment", main='Sentiment Analysis')
  }, height=400)
  
  #WordCloud
output$Wordcloud <- renderPlot({
  glimpse(df)
  set.seed(20)
  df <- df[sample(nrow(df)),]
  df <- df[sample(nrow(df)),]
  glimpse(df)

  corpus <- Corpus(VectorSource(df$text))
  corpus
  inspect(corpus[1:10])

  corpus.clean <- corpus %>%
    tm_map(content_transformer(tolower))%>%
    tm_map(removePunctuation)%>%
    tm_map(removeNumbers)%>%
    tm_map(removeWords, c("app", "saya", "bisa", "ini", "dan", "sangat", "aku" ,"untuk", "kalau", "tapi", "banget", "sih", "sudah", "masih","itu", "ada","yang","saja","tidak","nya","juga","dari","gak","aja","lebih"))%>%
    tm_map(removeWords,stopwords(kind="en"))%>%
    tm_map(stripWhitespace)
  dtm <- DocumentTermMatrix(corpus.clean)

  inspect(dtm[1:10, 1:20])

  df.train <- df[1:50,]
  df.test <- df[51:100,]

  dtm.train <- dtm[1:50,]
  dtm.test <- dtm[51:100,]

  corpus.clean.train <- corpus.clean[1:50]
  corpus.clean.test <- corpus.clean[51:100]

  dim(dtm.train)
  fivefreq <- findFreqTerms(dtm.train,5)
  length(fivefreq)

  dtm.train.nb <- DocumentTermMatrix(corpus.clean.train,control=list(dictionary=fivefreq))

  dtm.test.nb <- DocumentTermMatrix(corpus.clean.test,control=list(dictionary=fivefreq))

  dim(dtm.test.nb)

  convert_count <- function(x){
    y <- ifelse(x>0,1,0)
    y <- factor(y, levels=c(0,1), labels=c("no","yes"))
    y
  }
  trainNB <- apply(dtm.train.nb,2,convert_count)
  testNB <- apply(dtm.test.nb,1,convert_count)

  layout(matrix(c(1, 2), nrow=2), heights=c(1, 4))
  par(mar=rep(0, 4))
  plot.new()
  text(x=0.5, y=0.5, cex=1.5, "Word Cloud")
wordcloud(corpus.clean,max.words = 100,random.order=F,colors=brewer.pal(8,"Dark2"))

  })
}
shinyApp(ui = ui, server = server)
```



